"""HTML rendering: Check objects → the full static site under ``out_dir``.

This is the design layer. It owns exactly one public function,
:func:`render_site`, which ``build.py`` calls after the data layer has parsed
the cache into ``Check`` objects. Everything else here is private plumbing:

* a configured Jinja2 ``Environment`` (templates in ``templates/``),
* two custom filters (``datefmt``, ``jsonld``),
* per-page-type render helpers that compute groupings via ``content`` and
  hand ready-made JSON-LD dicts (built in ``seo``) to the templates.

Every page is written as ``<path>/index.html`` so the site works as plain
directories on any static host (clean URLs, no server rewrites). The one
exception is ``404.html`` at the site root, which Firebase serves for misses.

No network, no secrets, no state — a pure function of its ``checks`` argument.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import shutil
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape
from markupsafe import Markup

from . import seo
from .config import (
    HOME_RAIL_SIZE,
    HOME_SECTION_SIZE,
    HOME_STRIP_SIZE,
    PAGE_SIZE,
    RELATED_LIMIT,
    SECTIONS,
    SITE,
    SOURCES_SHOWN_MAX,
    VERDICT_ORDER,
)
from .content import (
    Check,
    EntityGroup,
    collections,
    group_by_entity,
    group_by_section,
    paginate,
    pick_lead,
    related_fallback,
)

logger = logging.getLogger(__name__)

_TEMPLATE_DIR = Path(__file__).parent / "templates"
_STATIC_DIR = Path(__file__).parent / "static"

#: Non-article pages share one default social card generated by ``ogimage.py``.
_DEFAULT_OG_PATH = "/og/site.png"

#: How many entities appear in the home-page "Frequently Checked" cloud.
_HOME_CLOUD_SIZE = 20  # 30 read as a link-wall at full catalog scale


# --------------------------------------------------------------------------- #
# Public contract
# --------------------------------------------------------------------------- #


def render_site(checks: list[Check], out_dir: Path) -> None:
    """Render the entire site from ``checks`` into ``out_dir``.

    ``checks`` is the newest-first list produced by ``content.build_checks``.
    All groupings (sections, entity hubs, collections, pagination) are derived
    here so the caller only has to pass the flat list. Idempotent: writes files,
    never reads prior output.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    css_path, css_body = _css_asset()
    env = _build_env()
    env.globals["CSS_PATH"] = css_path

    # Resolve related refs against *locally rendered* checks only — never link
    # to a claim that isn't on this site.
    by_id: dict[str, Check] = {c.verification_id: c for c in checks}

    sections = group_by_section(checks)  # every section key present (may be [])
    entity_groups = group_by_entity(checks)  # only entities with >= 2 claims
    colls = collections(checks)  # {"bs_files": [...], "checks_out": [...]}

    _render_home(env, out_dir, checks, sections, colls, entity_groups)
    _render_sections(env, out_dir, sections)
    topic_slugs = {g.entity.slug for g in entity_groups}
    _render_articles(env, out_dir, checks, by_id, topic_slugs)
    _render_topics(env, out_dir, entity_groups)
    _render_latest(env, out_dir, checks)
    _render_collections(env, out_dir, colls)
    _render_search(env, out_dir)
    _render_about(env, out_dir)
    _render_claim_stubs(env, out_dir, checks)
    _render_404(env, out_dir)

    _copy_static(out_dir, css_path, css_body)

    logger.info(
        "Rendered %d articles, %d section hubs, %d topics into %s",
        len(checks),
        len(SECTIONS),
        len(entity_groups),
        out_dir,
    )


# --------------------------------------------------------------------------- #
# Jinja environment
# --------------------------------------------------------------------------- #


def _build_env() -> Environment:
    """Configure the shared Jinja2 environment (globals + filters)."""
    env = Environment(
        loader=FileSystemLoader(str(_TEMPLATE_DIR)),
        autoescape=select_autoescape(["html", "xml"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    # Globals available in every template.
    env.globals["SITE"] = SITE
    env.globals["SECTIONS"] = SECTIONS
    env.globals["VERDICT_ORDER"] = VERDICT_ORDER
    env.globals["SOURCES_SHOWN_MAX"] = SOURCES_SHOWN_MAX
    env.globals["build_date"] = datetime.now(UTC).date()

    def claim_size_class(claim: str) -> str:
        """Graduated hero sizing — fold economics beat spectacle.

        Short claims earn the full display size; anything longer steps down
        so the verdict meter and the first answer paragraph stay above the
        fold on ordinary laptop viewports (measured: a 136-char claim at
        56px pushed the meter to 710px and the answer to 908px).
        """
        n = len(claim or "")
        if n > 120:
            return " claim-quote--long"
        if n > 60:
            return " claim-quote--medium"
        return ""

    env.globals["claim_size_class"] = claim_size_class
    # GA4 is opt-in at build time: set GA_MEASUREMENT_ID (e.g. a GitHub Actions
    # variable) and the gtag snippet ships; unset → zero analytics markup.
    # Never hardcoded — the public repo stays configuration-free.
    env.globals["GA_MEASUREMENT_ID"] = os.environ.get("GA_MEASUREMENT_ID", "")

    # Custom filters.
    env.filters["datefmt"] = _datefmt
    env.filters["jsonld"] = _jsonld
    return env


def _datefmt(value: str | datetime | date | None) -> str:
    """Format an ISO string or datetime as ``"Jul 23, 2026"``.

    Tolerant: empty/unparseable input returns the original string (or "").
    Uses explicit day/year interpolation instead of ``%-d`` so the output is
    identical across platforms.
    """
    if not value:
        return ""
    if isinstance(value, datetime):
        dt: datetime | date = value
    elif isinstance(value, date):
        dt = value
    else:
        try:
            dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except ValueError:
            return str(value)
    return f"{dt:%b} {dt.day}, {dt.year}"


def _jsonld(data: dict[str, Any]) -> Markup:
    """Serialize a JSON-LD dict into a safe ``<script>`` block.

    ``ensure_ascii=False`` keeps accented source names/claims human-readable;
    ``<`` is escaped to its unicode form so a stray ``</script>`` in the data
    can never break out of the tag (the payload stays valid JSON either way).
    """
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    payload = payload.replace("<", "\\u003c")
    return Markup(f'<script type="application/ld+json">{payload}</script>')


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #


def _truncate(text: str, limit: int) -> str:
    """Trim to ``limit`` chars on a word boundary, adding an ellipsis."""
    text = " ".join((text or "").split())
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0].rstrip(",.;:—- ") + "…"


def _meta_description(check: Check) -> str:
    """Verdict-first meta description with a receipts hook (SEO round 2).

    ``Verdict: X.`` catches is-it-true/false queries; the source count is the
    trust signal competitor snippets don't have. Budgeted to ~158 chars.
    """
    paras = check.summary_paragraphs
    body = paras[0] if paras else SITE.description
    # First sentence of the summary (fall back to the trimmed paragraph).
    sentence = body.split(". ")[0].rstrip(".") + "."
    prefix = f"Verdict: {check.verdict.key}. "
    suffix = (
        f" Checked against {len(check.sources)} independent sources."
        if check.sources
        else ""
    )
    budget = 158 - len(prefix) - len(suffix)
    return f"{prefix}{_truncate(sentence, max(40, budget))}{suffix}"


def _feed_path(base_path: str, page_no: int) -> str:
    """Site path for page ``page_no`` (1-based) of a paginated feed.

    Page 1 lives at ``base_path`` itself; later pages nest under ``page/N/``.
    """
    if page_no <= 1:
        return base_path
    return f"{base_path}page/{page_no}/"


def _write(out_dir: Path, url_path: str, html: str) -> None:
    """Write ``html`` to the clean-URL location for ``url_path``.

    ``"/"`` → ``out_dir/index.html``;
    ``"/health/"`` → ``out_dir/health/index.html``.
    """
    rel = url_path.strip("/")
    target = (out_dir / rel / "index.html") if rel else (out_dir / "index.html")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(html, encoding="utf-8")


def _resolve_related(
    check: Check, by_id: dict[str, Check], all_checks: list[Check]
) -> list[Check]:
    """Resolve a check's related refs to local Check objects (drop the rest).

    When the API gave us nothing (the related endpoint needs an API key;
    keyless builds get ``related: []``), fall back to local entity overlap so
    "MORE CHECKS" still renders.
    """
    resolved: list[Check] = []
    seen: set[str] = {check.verification_id}
    for ref in check.related:
        if ref.verification_id in seen:
            continue
        local = by_id.get(ref.verification_id)
        if local is not None:
            resolved.append(local)
            seen.add(ref.verification_id)
        if len(resolved) >= RELATED_LIMIT:
            break
    if not resolved:
        resolved = related_fallback(check, all_checks, limit=RELATED_LIMIT)
    return resolved


def _entity_cloud(groups: list[EntityGroup]) -> list[dict[str, Any]]:
    """Top entities for the home cloud, each with a 0..1 weight for sizing."""
    top = groups[:_HOME_CLOUD_SIZE]
    if not top:
        return []
    counts = [len(g.checks) for g in top]
    lo, hi = min(counts), max(counts)
    span = (hi - lo) or 1
    return [
        {
            "entity": g.entity,
            "count": len(g.checks),
            "weight": round((len(g.checks) - lo) / span, 3),
        }
        for g in top
    ]


# --------------------------------------------------------------------------- #
# Page renderers
# --------------------------------------------------------------------------- #


def _render_home(
    env: Environment,
    out_dir: Path,
    checks: list[Check],
    sections: dict[str, list[Check]],
    colls: dict[str, list[Check]],
    entity_groups: list[EntityGroup],
) -> None:
    """The front page: lead + fresh rail + strips + section blocks + cloud."""
    lead = pick_lead(checks)  # newest well-receipted check (E1 editorial floor)
    lead_id = lead.verification_id if lead else ""

    def sans_lead(items: list[Check]) -> list[Check]:
        """The lead story never repeats in another front-page slot."""
        return [c for c in items if c.verification_id != lead_id]

    rail = sans_lead(checks)[:HOME_RAIL_SIZE]

    # Per-section blocks: only sections that actually have checks, in nav order.
    section_blocks = [
        {"section": SECTIONS[key], "checks": sans_lead(items)[:HOME_SECTION_SIZE]}
        for key, items in sections.items()
        if sans_lead(items)
    ]

    html = env.get_template("home.html").render(
        nav_active="home",
        canonical_path="/",
        page_title=f"{SITE.name} — {SITE.tagline}",
        meta_description=SITE.description,
        og_type="website",
        og_image_path=_DEFAULT_OG_PATH,
        jsonld_blocks=[seo.organization(), seo.website()],
        lead=lead,
        rail=rail,
        bs_files=sans_lead(colls["bs_files"])[:HOME_STRIP_SIZE],
        checks_out=sans_lead(colls["checks_out"])[:HOME_STRIP_SIZE],
        section_blocks=section_blocks,
        entity_cloud=_entity_cloud(entity_groups),
    )
    _write(out_dir, "/", html)


def _render_sections(
    env: Environment, out_dir: Path, sections: dict[str, list[Check]]
) -> None:
    """8 section hubs, each paginated at PAGE_SIZE with verdict filter chips."""
    template = env.get_template("section.html")
    base_url = SITE.base_url
    for key, section in SECTIONS.items():
        items = sections.get(key, [])
        pages = paginate(items, PAGE_SIZE)
        total_pages = len(pages)
        breadcrumb = [("Home", "/"), (section.title, section.path)]
        for idx, page_items in enumerate(pages, start=1):
            url_path = _feed_path(section.path, idx)
            html = template.render(
                nav_active=key,
                canonical_path=url_path,
                page_title=f"{section.title} — Fact Checks · {SITE.short_name}",
                meta_description=(
                    f"{section.blurb} {len(items)} claims fact-checked so far."
                ),
                og_type="website",
                og_image_path=_DEFAULT_OG_PATH,
                jsonld_blocks=[
                    seo.item_list(page_items, base_url=base_url),
                    seo.breadcrumbs(breadcrumb, base_url=base_url),
                ],
                section=section,
                breadcrumb=breadcrumb,
                checks=page_items,
                page=idx,
                total_pages=total_pages,
                base_path=section.path,
            )
            _write(out_dir, url_path, html)


def _render_articles(
    env: Environment,
    out_dir: Path,
    checks: list[Check],
    by_id: dict[str, Check],
    topic_slugs: set[str],
) -> None:
    """One article per check — the core unit of the site."""
    template = env.get_template("article.html")
    base_url = SITE.base_url
    for check in checks:
        breadcrumb = [
            ("Home", "/"),
            (check.section.title, check.section.path),
            (_truncate(check.claim, 60), check.path),
        ]
        html = template.render(
            nav_active=check.section.key,
            canonical_path=check.path,
            # "Fact Check" = the query modifier; verdict = the answer in the
            # SERP; no brand suffix (Google shows the site name separately).
            page_title=(
                f"Fact Check: {_truncate(check.claim, 50)} — {check.verdict.key}"
            ),
            meta_description=_meta_description(check),
            og_type="article",
            og_image_path=check.og_path,
            jsonld_blocks=[
                seo.claim_review(check, base_url=base_url),
                seo.news_article(check, base_url=base_url),
                seo.breadcrumbs(breadcrumb, base_url=base_url),
            ],
            check=check,
            breadcrumb=breadcrumb[:2],  # visible crumb stops at the section
            related=_resolve_related(check, by_id, checks),
            # Entities with topic pages link there ("Filed Under" row); the
            # rest render unlinked — no dead links, and the row doubles as
            # the internal-link path that keeps topic hubs from being orphans.
            topic_slugs=topic_slugs,
        )
        _write(out_dir, check.path, html)


def _render_topics(
    env: Environment, out_dir: Path, entity_groups: list[EntityGroup]
) -> None:
    """Entity hubs (only entities with >= ENTITY_MIN_CLAIMS earn a page)."""
    template = env.get_template("topic.html")
    base_url = SITE.base_url
    for group in entity_groups:
        entity = group.entity
        members = list(group.checks)
        pages = paginate(members, PAGE_SIZE)
        total_pages = len(pages)
        breadcrumb = [("Home", "/"), (entity.name, entity.path)]
        for idx, page_items in enumerate(pages, start=1):
            url_path = _feed_path(entity.path, idx)
            html = template.render(
                nav_active=None,
                canonical_path=url_path,
                page_title=f"{entity.name} — Fact Checks · {SITE.short_name}",
                meta_description=(
                    f"{len(members)} claims mentioning {entity.name}, "
                    "each fact-checked against independent sources by Lenz."
                ),
                og_type="website",
                og_image_path=_DEFAULT_OG_PATH,
                jsonld_blocks=[
                    seo.item_list(page_items, base_url=base_url),
                    seo.breadcrumbs(breadcrumb, base_url=base_url),
                ],
                entity=entity,
                breadcrumb=breadcrumb,
                claim_count=len(members),
                checks=page_items,
                page=idx,
                total_pages=total_pages,
                base_path=entity.path,
            )
            _write(out_dir, url_path, html)


def _render_latest(env: Environment, out_dir: Path, checks: list[Check]) -> None:
    """Reverse-chron feed across all sections, paginated."""
    _render_feed_collection(
        env,
        out_dir,
        template_name="latest.html",
        base_path="/latest/",
        items=checks,
        nav_active="latest",
        page_title=f"Latest Checks · {SITE.short_name}",
        meta_description=(
            "The most recent claims checked by Lenz, newest first — across "
            "health, science, politics, finance, tech, history, and more."
        ),
        extra={"kicker": "LATEST", "heading": "Latest Checks"},
    )


def _render_collections(
    env: Environment, out_dir: Path, colls: dict[str, list[Check]]
) -> None:
    """The two computed collections: BS Files and Checks Out."""
    _render_feed_collection(
        env,
        out_dir,
        template_name="collection.html",
        base_path="/bs-files/",
        items=colls["bs_files"],
        nav_active=None,
        page_title=f"The BS Files · {SITE.short_name}",
        meta_description=(
            "Claims that didn't survive contact with the evidence — the "
            "False and Mostly False verdicts, collected."
        ),
        extra={
            "kicker": "COLLECTION",
            "heading": "The BS Files",
            "standfirst": "Claims that didn't survive contact with the evidence.",
        },
    )
    _render_feed_collection(
        env,
        out_dir,
        template_name="collection.html",
        base_path="/checks-out/",
        items=colls["checks_out"],
        nav_active=None,
        page_title=f"Checks Out · {SITE.short_name}",
        meta_description=(
            "Claims the evidence supports — the True and Mostly True "
            "verdicts, collected."
        ),
        extra={
            "kicker": "COLLECTION",
            "heading": "Checks Out",
            "standfirst": "Claims the evidence supports.",
        },
    )


def _render_feed_collection(
    env: Environment,
    out_dir: Path,
    *,
    template_name: str,
    base_path: str,
    items: list[Check],
    nav_active: str | None,
    page_title: str,
    meta_description: str,
    extra: dict[str, Any],
) -> None:
    """Shared driver for latest + collection pages (identical page mechanics)."""
    template = env.get_template(template_name)
    base_url = SITE.base_url
    pages = paginate(items, PAGE_SIZE)
    total_pages = len(pages)
    # Breadcrumb label from the heading; strip the leading article ("The …").
    label = extra.get("heading", page_title)
    breadcrumb = [("Home", "/"), (label, base_path)]
    for idx, page_items in enumerate(pages, start=1):
        url_path = _feed_path(base_path, idx)
        html = template.render(
            nav_active=nav_active,
            canonical_path=url_path,
            page_title=page_title,
            meta_description=meta_description,
            og_type="website",
            og_image_path=_DEFAULT_OG_PATH,
            jsonld_blocks=[
                seo.item_list(page_items, base_url=base_url),
                seo.breadcrumbs(breadcrumb, base_url=base_url),
            ],
            breadcrumb=breadcrumb,
            checks=page_items,
            page=idx,
            total_pages=total_pages,
            base_path=base_path,
            **extra,
        )
        _write(out_dir, url_path, html)


def _render_search(env: Environment, out_dir: Path) -> None:
    """The Pagefind-backed search page (client-side; assets lazy-loaded)."""
    html = env.get_template("search.html").render(
        nav_active="search",
        canonical_path="/search/",
        page_title=f"Search · {SITE.short_name}",
        meta_description=(
            "Search every claim IsThisBS has checked — by keyword, source, "
            "or topic. Filter by verdict."
        ),
        og_type="website",
        og_image_path=_DEFAULT_OG_PATH,
        breadcrumb=[("Home", "/"), ("Search", "/search/")],
    )
    _write(out_dir, "/search/", html)


def _render_about(env: Environment, out_dir: Path) -> None:
    """The methodology + disclosure + developer pitch page."""
    html = env.get_template("about.html").render(
        nav_active="about",
        canonical_path="/about/",
        page_title=f"About · {SITE.short_name}",
        meta_description=(
            "What IsThisBS is, how the checks work, what the BS Meter means, "
            "and how the whole site is built on the public Lenz API."
        ),
        og_type="website",
        og_image_path=_DEFAULT_OG_PATH,
        jsonld_blocks=[seo.organization(), seo.website()],
        breadcrumb=[("Home", "/"), ("About", "/about/")],
    )
    _write(out_dir, "/about/", html)


def _render_claim_stubs(env: Environment, out_dir: Path, checks: list[Check]) -> None:
    """Permanent /c/<id>/ short links -> canonical articles.

    The @isthisbs bot links claims by id the moment they're verified. Until
    the next build, Firebase rewrites the (nonexistent) path to the claimlive
    function; from then on these stubs shadow it. See claim_redirect.html.
    """
    template = env.get_template("claim_redirect.html")
    for check in checks:
        _write(
            out_dir,
            f"/c/{check.verification_id}/",
            template.render(check=check),
        )


def _render_404(env: Environment, out_dir: Path) -> None:
    """The not-found page — written to the site root, not a directory."""
    html = env.get_template("404.html").render(
        nav_active=None,
        canonical_path="/404.html",
        page_title=f"Not Found · {SITE.short_name}",
        meta_description="This page is BS — it doesn't exist.",
        og_type="website",
        og_image_path=_DEFAULT_OG_PATH,
    )
    (out_dir / "404.html").write_text(html, encoding="utf-8")


# --------------------------------------------------------------------------- #
# Static assets
# --------------------------------------------------------------------------- #


_CSS_SRC = "css/site.css"


def _minify_css(css: str) -> str:
    """Tiny whitespace/comment minifier for our own hand-written CSS.

    Not a general-purpose minifier — it only strips comments and collapses
    whitespace, which is safe for site.css (no data URIs with spaces, no
    string literals that need preserving).
    """
    import re

    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    css = re.sub(r"\s+", " ", css)
    css = re.sub(r"\s*([{}:;,>])\s*", r"\1", css)
    return css.replace(";}", "}").strip()


def _css_asset() -> tuple[str, str]:
    """(hashed public path, minified body) for the single stylesheet."""
    src = (_STATIC_DIR / _CSS_SRC).read_text(encoding="utf-8")
    mini = _minify_css(src)
    digest = hashlib.sha1(mini.encode("utf-8")).hexdigest()[:8]
    return f"/static/css/site.{digest}.css", mini


def _copy_static(out_dir: Path, css_path: str, css_body: str) -> None:
    """Copy ``static/**``, swap in the hashed/minified stylesheet, hoist favicon."""
    if not _STATIC_DIR.is_dir():
        logger.warning("Static directory missing: %s", _STATIC_DIR)
        return
    shutil.copytree(_STATIC_DIR, out_dir / "static", dirs_exist_ok=True)
    # The source stylesheet ships only under its content-hashed name.
    (out_dir / "static" / _CSS_SRC).unlink(missing_ok=True)
    hashed = out_dir / css_path.lstrip("/")
    hashed.parent.mkdir(parents=True, exist_ok=True)
    hashed.write_text(css_body, encoding="utf-8")
    favicon = _STATIC_DIR / "favicon.svg"
    if favicon.is_file():
        shutil.copyfile(favicon, out_dir / "favicon.svg")
